In [ ]:
import numpy as np
from numpy import ndarray
import pandas as pd
from pandas import DataFrame


scores = ndarray| None = None #學生的分數
scores_df = DataFrame| None = None #學生分數的DataFrame
# 就不用type hint。可以一進來就看出我們建立了多少變數

In [2]:
scores = np.random.randint(50, 101, size = (50, 5))
scores

array([[ 55,  96,  79,  89,  90],
       [ 94,  97,  79,  92,  71],
       [ 95,  50,  73,  72,  68],
       [ 87,  76,  55,  62,  61],
       [ 89,  86,  96,  72,  68],
       [ 88,  87,  58,  95,  79],
       [ 65,  87,  50,  67,  90],
       [ 78,  68,  84,  99,  98],
       [ 94,  81,  63, 100,  88],
       [ 67,  91,  61,  50,  67],
       [ 78,  56,  65,  82,  93],
       [ 96,  82,  81,  53,  85],
       [ 57,  67,  99,  78,  66],
       [ 54,  89,  76,  72,  97],
       [ 99,  70,  53,  52,  92],
       [ 60,  74,  59,  84,  98],
       [ 65,  50,  72,  76,  64],
       [ 57,  88,  78,  84,  59],
       [ 56,  57,  66,  91,  55],
       [ 87,  63,  51,  98, 100],
       [ 70,  60,  51,  66,  97],
       [ 75,  66,  74,  59,  64],
       [ 80,  75,  69,  99,  70],
       [ 74,  74,  94,  54,  57],
       [ 68,  83,  80,  77,  62],
       [ 78,  70,  77,  93,  93],
       [ 95,  57,  74,  65,  54],
       [ 96,  91,  78,  95,  75],
       [ 92,  98,  55,  98,  57],
       [ 50,  56,  76,  53,  53],
       [ 67,  62,  71,  64,  97],
       [ 91,  86,  82,  55,  60],
       [ 92,  54,  62,  65,  84],
       [ 71,  98,  73,  51,  92],
       [ 68,  76,  66,  56,  96],
       [ 85,  74,  72,  81,  53],
       [ 75,  94,  74,  97,  88],
       [ 84,  90,  70,  53,  97],
       [ 71,  74,  93,  89,  86],
       [ 74,  70,  68,  95,  63],
       [ 56,  81,  92,  51,  63],
       [ 81,  74,  95,  62,  60],
       [ 99,  50,  59,  84,  59],
       [ 54,  79,  71,  71,  97],
       [ 90,  62,  63,  64,  76],
       [ 69,  89,  57,  88,  71],
       [ 98,  83,  53,  56,  96],
       [ 74,  80,  77,  93,  63],
       [ 54,  62,  97,  79,  95],
       [ 66,  51,  68,  91,  63]])

In [3]:
pd.DataFrame(scores)

     0   1   2    3    4
0   55  96  79   89   90
1   94  97  79   92   71
2   95  50  73   72   68
3   87  76  55   62   61
4   89  86  96   72   68
5   88  87  58   95   79
6   65  87  50   67   90
7   78  68  84   99   98
8   94  81  63  100   88
9   67  91  61   50   67
10  78  56  65   82   93
11  96  82  81   53   85
12  57  67  99   78   66
13  54  89  76   72   97
14  99  70  53   52   92
15  60  74  59   84   98
16  65  50  72   76   64
17  57  88  78   84   59
18  56  57  66   91   55
19  87  63  51   98  100
20  70  60  51   66   97
21  75  66  74   59   64
22  80  75  69   99   70
23  74  74  94   54   57
24  68  83  80   77   62
25  78  70  77   93   93
26  95  57  74   65   54
27  96  91  78   95   75
28  92  98  55   98   57
29  50  56  76   53   53
30  67  62  71   64   97
31  91  86  82   55   60
32  92  54  62   65   84
33  71  98  73   51   92
34  68  76  66   56   96
35  85  74  72   81   53
36  75  94  74   97   88
37  84  90  70   53   97
38  71  74  93   89   86
39  74  70  68   95   63
40  56  81  92   51   63
41  81  74  95   62   60
42  99  50  59   84   59
43  54  79  71   71   97
44  90  62  63   64   76
45  69  89  57   88   71
46  98  83  53   56   96
47  74  80  77   93   63
48  54  62  97   79   95
49  66  51  68   91   63

In [ ]:
scores_df : DataFrame = pd.DataFrame(scores,range(1,51),["語文","英語","數學","地理","歷史"])
# pd.DataFrame(scores,range(1,51),["語文","英語","數學","地理","歷史"])
# pd.DataFrame(scores,
#              index = range(1,51),
#              columns = ["語文","英語","數學","地理","歷史"])
print(scores_df)

    語文  英語  數學   地理   歷史
1   55  96  79   89   90
2   94  97  79   92   71
3   95  50  73   72   68
4   87  76  55   62   61
5   89  86  96   72   68
6   88  87  58   95   79
7   65  87  50   67   90
8   78  68  84   99   98
9   94  81  63  100   88
10  67  91  61   50   67
11  78  56  65   82   93
12  96  82  81   53   85
13  57  67  99   78   66
14  54  89  76   72   97
15  99  70  53   52   92
16  60  74  59   84   98
17  65  50  72   76   64
18  57  88  78   84   59
19  56  57  66   91   55
20  87  63  51   98  100
21  70  60  51   66   97
22  75  66  74   59   64
23  80  75  69   99   70
24  74  74  94   54   57
25  68  83  80   77   62
26  78  70  77   93   93
27  95  57  74   65   54
28  96  91  78   95   75
29  92  98  55   98   57
30  50  56  76   53   53
31  67  62  71   64   97
32  91  86  82   55   60
33  92  54  62   65   84
34  71  98  73   51   92
35  68  76  66   56   96
36  85  74  72   81   53
37  75  94  74   97   88
38  84  90  70   53   97
39  71  74  93   89   86
40  74  70  68   95   63
41  56  81  92   51   63
42  81  74  95   62   60
43  99  50  59   84   59
44  54  79  71   71   97
45  90  62  63   64   76
46  69  89  57   88   71
47  98  83  53   56   96
48  74  80  77   93   63
49  54  62  97   79   95
50  66  51  68   91   63

In [ ]:
scores_df.T
# 欄列對調。後面可以做樞紐分析

,1,2,3,4,5,6,7,8,9,10,...,41,42,43,44,45,46,47,48,49,50
語文,55,94,95,87,89,88,65,78,94,67,...,56,81,99,54,90,69,98,74,54,66
英語,96,97,50,76,86,87,87,68,81,91,...,81,74,50,79,62,89,83,80,62,51
數學,79,79,73,55,96,58,50,84,63,61,...,92,95,59,71,63,57,53,77,97,68
地理,89,92,72,62,72,95,67,99,100,50,...,51,62,84,71,64,88,56,93,79,91
歷史,90,71,68,61,68,79,90,98,88,67,...,63,60,59,97,76,71,96,63,95,63