In [24]:
import numpy as np
from numpy import ndarray
import pandas as pd
from pandas import DataFrame


scores : ndarray #| None = None #學生的分數
scores_df : DataFrame #| None = None #學生分數的DataFrame
# 就不用type hint。可以一進來就看出我們建立了多少變數

In [28]:
scores = np.random.randint(50, 101, size = (50, 5))
scores

array([[ 54,  69,  69,  95,  57],
       [ 64,  90,  67,  60,  93],
       [ 86,  57,  65,  72,  66],
       [ 63,  94,  78,  52,  78],
       [ 85,  85,  90,  66,  55],
       [ 59,  86,  51,  87,  74],
       [ 50,  85,  52,  54,  58],
       [ 61,  93,  86,  51,  67],
       [ 93,  64,  69,  86,  94],
       [ 60,  60,  98,  90,  66],
       [ 71,  66,  61,  62,  72],
       [ 50,  79,  86,  60,  64],
       [ 72,  75,  84,  80,  96],
       [ 63,  57,  53, 100,  60],
       [ 81,  66,  72,  53,  59],
       [ 60,  85,  58,  59,  87],
       [ 77,  54,  50,  68,  87],
       [ 83,  50,  52,  55,  60],
       [ 94,  77,  76,  79,  55],
       [ 60,  94,  50,  92,  94],
       [ 64,  55,  83,  60,  88],
       [ 61,  77,  69,  54,  56],
       [ 66,  71,  50,  68,  95],
       [ 92,  83,  54,  93,  55],
       [ 63,  97,  80,  94,  54],
       [ 82,  83, 100,  62,  51],
       [ 71,  89,  94,  89,  93],
       [ 57,  80,  98,  75,  94],
       [100,  83,  52,  60,  71],
       [ 65,  96,  76,  76,  98],
       [ 53,  52,  78,  54,  74],
       [ 88,  50,  98,  52,  77],
       [ 95,  54,  68,  56,  84],
       [ 69,  64,  64,  51,  97],
       [ 80, 100,  72,  67,  56],
       [ 97,  94,  51,  65,  70],
       [ 95,  60,  96,  75,  76],
       [ 91,  68,  68,  78,  75],
       [ 96,  97,  72,  94,  99],
       [ 66,  70,  67,  72,  66],
       [ 64,  70,  88,  61,  92],
       [ 72,  91,  60,  91,  83],
       [ 98,  58,  55,  69,  83],
       [ 86,  53,  61,  71,  88],
       [ 68,  96,  66,  66,  56],
       [ 51,  81,  67,  85,  78],
       [ 94,  99,  73,  99,  50],
       [ 80,  91,  87,  67,  97],
       [ 90,  56,  76,  91,  69],
       [ 52,  63,  84,  59,  59]])

In [29]:
pd.DataFrame(scores)

      0    1    2    3   4
0    54   69   69   95  57
1    64   90   67   60  93
2    86   57   65   72  66
3    63   94   78   52  78
4    85   85   90   66  55
5    59   86   51   87  74
6    50   85   52   54  58
7    61   93   86   51  67
8    93   64   69   86  94
9    60   60   98   90  66
10   71   66   61   62  72
11   50   79   86   60  64
12   72   75   84   80  96
13   63   57   53  100  60
14   81   66   72   53  59
15   60   85   58   59  87
16   77   54   50   68  87
17   83   50   52   55  60
18   94   77   76   79  55
19   60   94   50   92  94
20   64   55   83   60  88
21   61   77   69   54  56
22   66   71   50   68  95
23   92   83   54   93  55
24   63   97   80   94  54
25   82   83  100   62  51
26   71   89   94   89  93
27   57   80   98   75  94
28  100   83   52   60  71
29   65   96   76   76  98
30   53   52   78   54  74
31   88   50   98   52  77
32   95   54   68   56  84
33   69   64   64   51  97
34   80  100   72   67  56
35   97   94   51   65  70
36   95   60   96   75  76
37   91   68   68   78  75
38   96   97   72   94  99
39   66   70   67   72  66
40   64   70   88   61  92
41   72   91   60   91  83
42   98   58   55   69  83
43   86   53   61   71  88
44   68   96   66   66  56
45   51   81   67   85  78
46   94   99   73   99  50
47   80   91   87   67  97
48   90   56   76   91  69
49   52   63   84   59  59

In [30]:
scores_df : DataFrame = pd.DataFrame(scores,range(1,51),["語文","英語","數學","地理","歷史"])
# pd.DataFrame(scores,range(1,51),["語文","英語","數學","地理","歷史"])
# pd.DataFrame(scores,
#              index = range(1,51),
#              columns = ["語文","英語","數學","地理","歷史"])
print(scores_df)

     語文   英語   數學   地理  歷史
1    54   69   69   95  57
2    64   90   67   60  93
3    86   57   65   72  66
4    63   94   78   52  78
5    85   85   90   66  55
6    59   86   51   87  74
7    50   85   52   54  58
8    61   93   86   51  67
9    93   64   69   86  94
10   60   60   98   90  66
11   71   66   61   62  72
12   50   79   86   60  64
13   72   75   84   80  96
14   63   57   53  100  60
15   81   66   72   53  59
16   60   85   58   59  87
17   77   54   50   68  87
18   83   50   52   55  60
19   94   77   76   79  55
20   60   94   50   92  94
21   64   55   83   60  88
22   61   77   69   54  56
23   66   71   50   68  95
24   92   83   54   93  55
25   63   97   80   94  54
26   82   83  100   62  51
27   71   89   94   89  93
28   57   80   98   75  94
29  100   83   52   60  71
30   65   96   76   76  98
31   53   52   78   54  74
32   88   50   98   52  77
33   95   54   68   56  84
34   69   64   64   51  97
35   80  100   72   67  56
36   97   94   51   65  70
37   95   60   96   75  76
38   91   68   68   78  75
39   96   97   72   94  99
40   66   70   67   72  66
41   64   70   88   61  92
42   72   91   60   91  83
43   98   58   55   69  83
44   86   53   61   71  88
45   68   96   66   66  56
46   51   81   67   85  78
47   94   99   73   99  50
48   80   91   87   67  97
49   90   56   76   91  69
50   52   63   84   59  59

In [31]:
scores_df.T
# 欄列對調。後面可以做樞紐分析

,1,2,3,4,5,6,7,8,9,10,...,41,42,43,44,45,46,47,48,49,50
語文,54,64,86,63,85,59,50,61,93,60,...,64,72,98,86,68,51,94,80,90,52
英語,69,90,57,94,85,86,85,93,64,60,...,70,91,58,53,96,81,99,91,56,63
數學,69,67,65,78,90,51,52,86,69,98,...,88,60,55,61,66,67,73,87,76,84
地理,95,60,72,52,66,87,54,51,86,90,...,61,91,69,71,66,85,99,67,91,59
歷史,57,93,66,78,55,74,58,67,94,66,...,92,83,83,88,56,78,50,97,69,59

In [46]:
print(type(scores_df))

names_df:DataFrame = pd.read_csv('students.csv')
scores_df[['姓名','性別']] = names_df[['姓名','性別']].head(n=50).values
scores_df = scores_df[['姓名', '性別','語文','英語', '數學', '地理', '歷史']]
scores_df


#選取欄
scores_df[['姓名','語文']]
#選取列
scores_df.iloc[5]
scores_df.iloc[5:10]

<class 'pandas.DataFrame'>

     姓名 性別  語文  英語  數學  地理  歷史
6   朱冠霖  男  59  86  51  87  74
7   謝欣蓉  女  50  85  52  54  58
8   羅淑芬  女  61  93  86  51  67
9   許美慧  女  93  64  69  86  94
10  廖志豪  男  60  60  98  90  66

In [48]:
scores_df['姓名'] == '朱冠霖'
# 用照樣的方法是看布林值

1     False
2     False
3     False
4     False
5     False
6      True
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24    False
25    False
26    False
27    False
28    False
29    False
30    False
31    False
32    False
33    False
34    False
35    False
36    False
37    False
38    False
39    False
40    False
41    False
42    False
43    False
44    False
45    False
46    False
47    False
48    False
49    False
50    False
Name: 姓名, dtype: bool

In [52]:
scores_df[scores_df['姓名'] == '朱冠霖']

    姓名 性別  語文  英語  數學  地理  歷史
6  朱冠霖  男  59  86  51  87  74

In [53]:
scores_df[scores_df['歷史'] < 60]

     姓名 性別  語文   英語   數學  地理  歷史
1   劉彥宏  男  54   69   69  95  57
5   王文傑  男  85   85   90  66  55
7   謝欣蓉  女  50   85   52  54  58
15  王婉茹  女  81   66   72  53  59
19  呂婉慧  女  94   77   76  79  55
22  李柏融  男  61   77   69  54  56
24  呂佳瑩  女  92   83   54  93  55
25  洪怡君  女  63   97   80  94  54
26  洪柏宏  男  82   83  100  62  51
35  劉浩然  男  80  100   72  67  56
45  莊柏融  男  68   96   66  66  56
47  周美玲  女  94   99   73  99  50
50  詹柏翰  男  52   63   84  59  59