In [10]:
import numpy as np
from numpy import ndarray
import pandas as pd
from pandas import DataFrame


scores : ndarray #| None = None #學生的分數
scores_df : DataFrame #| None = None #學生分數的DataFrame
# 就不用type hint。可以一進來就看出我們建立了多少變數

In [11]:
scores = np.random.randint(50, 101, size = (50, 5))
scores

array([[ 64,  69,  72,  73,  86],
       [ 60,  77,  56,  89,  89],
       [ 75,  94,  66,  99,  91],
       [ 88,  98,  51,  70,  89],
       [ 87,  53,  53,  67,  63],
       [ 80,  74,  96,  60,  89],
       [ 59,  65,  51,  83,  61],
       [ 52,  68,  69,  68,  98],
       [ 80,  71,  95,  88,  65],
       [ 93,  60,  84,  52,  97],
       [ 80,  97,  98,  55,  88],
       [ 51,  60,  54,  50,  56],
       [ 50,  62,  75,  95,  84],
       [ 82, 100,  92,  97,  92],
       [ 65,  79,  89,  87,  68],
       [ 69,  56,  70,  54,  83],
       [ 86,  83,  87,  83,  64],
       [ 72,  70,  64,  70,  69],
       [ 67,  92,  85,  99,  82],
       [ 67,  81,  57,  77,  60],
       [ 78,  65,  92,  98,  69],
       [ 91,  74,  96,  84,  76],
       [ 98,  82,  73,  71,  62],
       [ 95,  72,  52,  74,  92],
       [ 50,  77,  95,  99,  86],
       [ 58, 100,  61,  66,  67],
       [ 89,  98,  88,  71,  61],
       [ 88,  87,  60,  86,  68],
       [ 90,  89,  91,  98,  93],
       [ 51,  98,  65,  98,  54],
       [ 86,  63,  65,  50,  95],
       [ 61,  88,  95,  75,  78],
       [ 97,  83,  96,  77,  61],
       [ 77,  60,  66,  75,  82],
       [ 86,  63,  70,  67,  65],
       [ 88,  89,  78,  74,  89],
       [ 50,  94,  72,  76,  87],
       [ 57,  59,  58,  81,  94],
       [ 91,  52,  95,  53,  60],
       [ 63,  91,  96,  63,  56],
       [ 97,  91,  70,  85,  84],
       [ 57, 100,  65,  80,  64],
       [ 55,  99,  86,  95,  89],
       [ 69,  92,  63,  61,  95],
       [ 70,  94,  89,  62,  97],
       [ 69,  65,  61,  85,  89],
       [ 72,  58,  94,  61,  99],
       [ 95,  76,  78,  72,  51],
       [ 50,  89,  84,  94,  64],
       [ 96,  69,  80,  66,  51]])

In [12]:
pd.DataFrame(scores)

     0    1   2   3   4
0   64   69  72  73  86
1   60   77  56  89  89
2   75   94  66  99  91
3   88   98  51  70  89
4   87   53  53  67  63
5   80   74  96  60  89
6   59   65  51  83  61
7   52   68  69  68  98
8   80   71  95  88  65
9   93   60  84  52  97
10  80   97  98  55  88
11  51   60  54  50  56
12  50   62  75  95  84
13  82  100  92  97  92
14  65   79  89  87  68
15  69   56  70  54  83
16  86   83  87  83  64
17  72   70  64  70  69
18  67   92  85  99  82
19  67   81  57  77  60
20  78   65  92  98  69
21  91   74  96  84  76
22  98   82  73  71  62
23  95   72  52  74  92
24  50   77  95  99  86
25  58  100  61  66  67
26  89   98  88  71  61
27  88   87  60  86  68
28  90   89  91  98  93
29  51   98  65  98  54
30  86   63  65  50  95
31  61   88  95  75  78
32  97   83  96  77  61
33  77   60  66  75  82
34  86   63  70  67  65
35  88   89  78  74  89
36  50   94  72  76  87
37  57   59  58  81  94
38  91   52  95  53  60
39  63   91  96  63  56
40  97   91  70  85  84
41  57  100  65  80  64
42  55   99  86  95  89
43  69   92  63  61  95
44  70   94  89  62  97
45  69   65  61  85  89
46  72   58  94  61  99
47  95   76  78  72  51
48  50   89  84  94  64
49  96   69  80  66  51

In [13]:
scores_df : DataFrame = pd.DataFrame(scores,range(1,51),["語文","英語","數學","地理","歷史"])
# pd.DataFrame(scores,range(1,51),["語文","英語","數學","地理","歷史"])
# pd.DataFrame(scores,
#              index = range(1,51),
#              columns = ["語文","英語","數學","地理","歷史"])
print(scores_df)

    語文   英語  數學  地理  歷史
1   64   69  72  73  86
2   60   77  56  89  89
3   75   94  66  99  91
4   88   98  51  70  89
5   87   53  53  67  63
6   80   74  96  60  89
7   59   65  51  83  61
8   52   68  69  68  98
9   80   71  95  88  65
10  93   60  84  52  97
11  80   97  98  55  88
12  51   60  54  50  56
13  50   62  75  95  84
14  82  100  92  97  92
15  65   79  89  87  68
16  69   56  70  54  83
17  86   83  87  83  64
18  72   70  64  70  69
19  67   92  85  99  82
20  67   81  57  77  60
21  78   65  92  98  69
22  91   74  96  84  76
23  98   82  73  71  62
24  95   72  52  74  92
25  50   77  95  99  86
26  58  100  61  66  67
27  89   98  88  71  61
28  88   87  60  86  68
29  90   89  91  98  93
30  51   98  65  98  54
31  86   63  65  50  95
32  61   88  95  75  78
33  97   83  96  77  61
34  77   60  66  75  82
35  86   63  70  67  65
36  88   89  78  74  89
37  50   94  72  76  87
38  57   59  58  81  94
39  91   52  95  53  60
40  63   91  96  63  56
41  97   91  70  85  84
42  57  100  65  80  64
43  55   99  86  95  89
44  69   92  63  61  95
45  70   94  89  62  97
46  69   65  61  85  89
47  72   58  94  61  99
48  95   76  78  72  51
49  50   89  84  94  64
50  96   69  80  66  51

In [14]:
scores_df.T
# 欄列對調。後面可以做樞紐分析

,1,2,3,4,5,6,7,8,9,10,...,41,42,43,44,45,46,47,48,49,50
語文,64,60,75,88,87,80,59,52,80,93,...,97,57,55,69,70,69,72,95,50,96
英語,69,77,94,98,53,74,65,68,71,60,...,91,100,99,92,94,65,58,76,89,69
數學,72,56,66,51,53,96,51,69,95,84,...,70,65,86,63,89,61,94,78,84,80
地理,73,89,99,70,67,60,83,68,88,52,...,85,80,95,61,62,85,61,72,94,66
歷史,86,89,91,89,63,89,61,98,65,97,...,84,64,89,95,97,89,99,51,64,51

In [15]:
print(type(scores_df))

names_df:DataFrame = pd.read_csv('students.csv')
scores_df[['姓名','性別']] = names_df[['姓名','性別']].head(n=50).values
scores_df = scores_df[['姓名', '性別','語文','英語', '數學', '地理', '歷史']]
scores_df


#選取欄
scores_df[['姓名','語文']]
#選取列
scores_df.iloc[5]
scores_df.iloc[5:10]

<class 'pandas.DataFrame'>

     姓名 性別  語文  英語  數學  地理  歷史
6   朱冠霖  男  80  74  96  60  89
7   謝欣蓉  女  59  65  51  83  61
8   羅淑芬  女  52  68  69  68  98
9   許美慧  女  80  71  95  88  65
10  廖志豪  男  93  60  84  52  97

In [16]:
scores_df['姓名'] == '朱冠霖'
# 用照樣的方法是看布林值

1     False
2     False
3     False
4     False
5     False
6      True
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24    False
25    False
26    False
27    False
28    False
29    False
30    False
31    False
32    False
33    False
34    False
35    False
36    False
37    False
38    False
39    False
40    False
41    False
42    False
43    False
44    False
45    False
46    False
47    False
48    False
49    False
50    False
Name: 姓名, dtype: bool

In [17]:
scores_df[scores_df['姓名'] == '朱冠霖']

    姓名 性別  語文  英語  數學  地理  歷史
6  朱冠霖  男  80  74  96  60  89

In [18]:
scores_df[scores_df['歷史'] < 60]

     姓名 性別  語文  英語  數學  地理  歷史
12  呂承恩  男  51  60  54  50  56
30  楊靜宜  女  51  98  65  98  54
40  劉靜芬  女  63  91  96  63  56
48  劉婉婷  女  95  76  78  72  51
50  詹柏翰  男  96  69  80  66  51

In [19]:
scores_df.query("性別 == '男' and 英語 > 90")

     姓名 性別  語文   英語  數學  地理  歷史
3   吳子睿  男  75   94  66  99  91
4   蕭志明  男  88   98  51  70  89
11  葉柏翰  男  80   97  98  55  88
14  高浩宇  男  82  100  92  97  92
26  洪柏宏  男  58  100  61  66  67
42  邱裕豪  男  57  100  65  80  64
44  施子軒  男  69   92  63  61  95
45  莊柏融  男  70   94  89  62  97

In [20]:
scores_df[['語文','英語', '數學', '地理', '歷史']].sum(axis = 0)

語文    3701
英語    3926
數學    3798
地理    3813
歷史    3852
dtype: int64

In [21]:
scores_df[['語文','英語', '數學', '地理', '歷史']].sum(axis = 1)

1     364
2     371
3     425
4     396
5     323
6     399
7     319
8     355
9     399
10    386
11    418
12    271
13    366
14    463
15    388
16    332
17    403
18    345
19    425
20    342
21    402
22    421
23    386
24    385
25    407
26    352
27    407
28    389
29    461
30    366
31    359
32    397
33    414
34    360
35    351
36    418
37    379
38    349
39    351
40    369
41    427
42    366
43    424
44    380
45    412
46    369
47    384
48    372
49    381
50    362
dtype: int64

In [22]:
scores_df['總分'] = scores_df[['語文','英語', '數學', '地理', '歷史']].sum(axis = 1)
scores_df['平均'] = scores_df[['語文','英語', '數學', '地理', '歷史']].mean(axis = 1)
scores_df

     姓名 性別  語文   英語  數學  地理  歷史   總分    平均
1   劉彥宏  男  64   69  72  73  86  364  72.8
2   曾彥廷  男  60   77  56  89  89  371  74.2
3   吳子睿  男  75   94  66  99  91  425  85.0
4   蕭志明  男  88   98  51  70  89  396  79.2
5   王文傑  男  87   53  53  67  63  323  64.6
6   朱冠霖  男  80   74  96  60  89  399  79.8
7   謝欣蓉  女  59   65  51  83  61  319  63.8
8   羅淑芬  女  52   68  69  68  98  355  71.0
9   許美慧  女  80   71  95  88  65  399  79.8
10  廖志豪  男  93   60  84  52  97  386  77.2
11  葉柏翰  男  80   97  98  55  88  418  83.6
12  呂承恩  男  51   60  54  50  56  271  54.2
13  蘇雅婷  女  50   62  75  95  84  366  73.2
14  高浩宇  男  82  100  92  97  92  463  92.6
15  王婉茹  女  65   79  89  87  68  388  77.6
16  莊承翰  男  69   56  70  54  83  332  66.4
17  黃裕傑  男  86   83  87  83  64  403  80.6
18  王冠廷  男  72   70  64  70  69  345  69.0
19  呂婉慧  女  67   92  85  99  82  425  85.0
20  莊子謙  男  67   81  57  77  60  342  68.4
21  蘇彥宏  男  78   65  92  98  69  402  80.4
22  李柏融  男  91   74  96  84  76  421  84.2
23  曾明軒  男  98   82  73  71  62  386  77.2
24  呂佳瑩  女  95   72  52  74  92  385  77.0
25  洪怡君  女  50   77  95  99  86  407  81.4
26  洪柏宏  男  58  100  61  66  67  352  70.4
27  江雅琪  女  89   98  88  71  61  407  81.4
28  郭怡萱  女  88   87  60  86  68  389  77.8
29  簡婉慧  女  90   89  91  98  93  461  92.2
30  楊靜宜  女  51   98  65  98  54  366  73.2
31  曾靜儀  女  86   63  65  50  95  359  71.8
32  蕭怡伶  女  61   88  95  75  78  397  79.4
33  洪裕豪  男  97   83  96  77  61  414  82.8
34  簡建宏  男  77   60  66  75  82  360  72.0
35  劉浩然  男  86   63  70  67  65  351  70.2
36  蕭浩宇  男  88   89  78  74  89  418  83.6
37  呂怡靜  女  50   94  72  76  87  379  75.8
38  邱宗翰  男  57   59  58  81  94  349  69.8
39  彭美慧  女  91   52  95  53  60  351  70.2
40  劉靜芬  女  63   91  96  63  56  369  73.8
41  許淑芬  女  97   91  70  85  84  427  85.4
42  邱裕豪  男  57  100  65  80  64  366  73.2
43  吳雅萍  女  55   99  86  95  89  424  84.8
44  施子軒  男  69   92  63  61  95  380  76.0
45  莊柏融  男  70   94  89  62  97  412  82.4
46  鍾浩銘  男  69   65  61  85  89  369  73.8
47  周美玲  女  72   58  94  61  99  384  76.8
48  劉婉婷  女  95   76  78  72  51  372  74.4
49  曾明哲  男  50   89  84  94  64  381  76.2
50  詹柏翰  男  96   69  80  66  51  362  72.4

In [23]:
scores_df['排名'] = scores_df[['總分']].rank(ascending = False, method = 'min')
scores_df.sort_values(by = '排名')

     姓名 性別  語文   英語  數學  地理  歷史   總分    平均    排名
14  高浩宇  男  82  100  92  97  92  463  92.6   1.0
29  簡婉慧  女  90   89  91  98  93  461  92.2   2.0
41  許淑芬  女  97   91  70  85  84  427  85.4   3.0
19  呂婉慧  女  67   92  85  99  82  425  85.0   4.0
3   吳子睿  男  75   94  66  99  91  425  85.0   4.0
43  吳雅萍  女  55   99  86  95  89  424  84.8   6.0
22  李柏融  男  91   74  96  84  76  421  84.2   7.0
11  葉柏翰  男  80   97  98  55  88  418  83.6   8.0
36  蕭浩宇  男  88   89  78  74  89  418  83.6   8.0
33  洪裕豪  男  97   83  96  77  61  414  82.8  10.0
45  莊柏融  男  70   94  89  62  97  412  82.4  11.0
25  洪怡君  女  50   77  95  99  86  407  81.4  12.0
27  江雅琪  女  89   98  88  71  61  407  81.4  12.0
17  黃裕傑  男  86   83  87  83  64  403  80.6  14.0
21  蘇彥宏  男  78   65  92  98  69  402  80.4  15.0
9   許美慧  女  80   71  95  88  65  399  79.8  16.0
6   朱冠霖  男  80   74  96  60  89  399  79.8  16.0
32  蕭怡伶  女  61   88  95  75  78  397  79.4  18.0
4   蕭志明  男  88   98  51  70  89  396  79.2  19.0
28  郭怡萱  女  88   87  60  86  68  389  77.8  20.0
15  王婉茹  女  65   79  89  87  68  388  77.6  21.0
10  廖志豪  男  93   60  84  52  97  386  77.2  22.0
23  曾明軒  男  98   82  73  71  62  386  77.2  22.0
24  呂佳瑩  女  95   72  52  74  92  385  77.0  24.0
47  周美玲  女  72   58  94  61  99  384  76.8  25.0
49  曾明哲  男  50   89  84  94  64  381  76.2  26.0
44  施子軒  男  69   92  63  61  95  380  76.0  27.0
37  呂怡靜  女  50   94  72  76  87  379  75.8  28.0
48  劉婉婷  女  95   76  78  72  51  372  74.4  29.0
2   曾彥廷  男  60   77  56  89  89  371  74.2  30.0
40  劉靜芬  女  63   91  96  63  56  369  73.8  31.0
46  鍾浩銘  男  69   65  61  85  89  369  73.8  31.0
42  邱裕豪  男  57  100  65  80  64  366  73.2  33.0
13  蘇雅婷  女  50   62  75  95  84  366  73.2  33.0
30  楊靜宜  女  51   98  65  98  54  366  73.2  33.0
1   劉彥宏  男  64   69  72  73  86  364  72.8  36.0
50  詹柏翰  男  96   69  80  66  51  362  72.4  37.0
34  簡建宏  男  77   60  66  75  82  360  72.0  38.0
31  曾靜儀  女  86   63  65  50  95  359  71.8  39.0
8   羅淑芬  女  52   68  69  68  98  355  71.0  40.0
26  洪柏宏  男  58  100  61  66  67  352  70.4  41.0
35  劉浩然  男  86   63  70  67  65  351  70.2  42.0
39  彭美慧  女  91   52  95  53  60  351  70.2  42.0
38  邱宗翰  男  57   59  58  81  94  349  69.8  44.0
18  王冠廷  男  72   70  64  70  69  345  69.0  45.0
20  莊子謙  男  67   81  57  77  60  342  68.4  46.0
16  莊承翰  男  69   56  70  54  83  332  66.4  47.0
5   王文傑  男  87   53  53  67  63  323  64.6  48.0
7   謝欣蓉  女  59   65  51  83  61  319  63.8  49.0
12  呂承恩  男  51   60  54  50  56  271  54.2  50.0

In [25]:
from pandas import Series
def caculate (s:Series)-> int:
    n = (s < 60).sum()
    return n

scores_df['及格科目數'] = scores_df[['語文','英語', '數學', '地理', '歷史']].apply(caculate, axis =1)
scores_df

     姓名 性別  語文   英語  數學  地理  歷史   總分    平均    排名  及格科目數
1   劉彥宏  男  64   69  72  73  86  364  72.8  36.0      0
2   曾彥廷  男  60   77  56  89  89  371  74.2  30.0      1
3   吳子睿  男  75   94  66  99  91  425  85.0   4.0      0
4   蕭志明  男  88   98  51  70  89  396  79.2  19.0      1
5   王文傑  男  87   53  53  67  63  323  64.6  48.0      2
6   朱冠霖  男  80   74  96  60  89  399  79.8  16.0      0
7   謝欣蓉  女  59   65  51  83  61  319  63.8  49.0      2
8   羅淑芬  女  52   68  69  68  98  355  71.0  40.0      1
9   許美慧  女  80   71  95  88  65  399  79.8  16.0      0
10  廖志豪  男  93   60  84  52  97  386  77.2  22.0      1
11  葉柏翰  男  80   97  98  55  88  418  83.6   8.0      1
12  呂承恩  男  51   60  54  50  56  271  54.2  50.0      4
13  蘇雅婷  女  50   62  75  95  84  366  73.2  33.0      1
14  高浩宇  男  82  100  92  97  92  463  92.6   1.0      0
15  王婉茹  女  65   79  89  87  68  388  77.6  21.0      0
16  莊承翰  男  69   56  70  54  83  332  66.4  47.0      2
17  黃裕傑  男  86   83  87  83  64  403  80.6  14.0      0
18  王冠廷  男  72   70  64  70  69  345  69.0  45.0      0
19  呂婉慧  女  67   92  85  99  82  425  85.0   4.0      0
20  莊子謙  男  67   81  57  77  60  342  68.4  46.0      1
21  蘇彥宏  男  78   65  92  98  69  402  80.4  15.0      0
22  李柏融  男  91   74  96  84  76  421  84.2   7.0      0
23  曾明軒  男  98   82  73  71  62  386  77.2  22.0      0
24  呂佳瑩  女  95   72  52  74  92  385  77.0  24.0      1
25  洪怡君  女  50   77  95  99  86  407  81.4  12.0      1
26  洪柏宏  男  58  100  61  66  67  352  70.4  41.0      1
27  江雅琪  女  89   98  88  71  61  407  81.4  12.0      0
28  郭怡萱  女  88   87  60  86  68  389  77.8  20.0      0
29  簡婉慧  女  90   89  91  98  93  461  92.2   2.0      0
30  楊靜宜  女  51   98  65  98  54  366  73.2  33.0      2
31  曾靜儀  女  86   63  65  50  95  359  71.8  39.0      1
32  蕭怡伶  女  61   88  95  75  78  397  79.4  18.0      0
33  洪裕豪  男  97   83  96  77  61  414  82.8  10.0      0
34  簡建宏  男  77   60  66  75  82  360  72.0  38.0      0
35  劉浩然  男  86   63  70  67  65  351  70.2  42.0      0
36  蕭浩宇  男  88   89  78  74  89  418  83.6   8.0      0
37  呂怡靜  女  50   94  72  76  87  379  75.8  28.0      1
38  邱宗翰  男  57   59  58  81  94  349  69.8  44.0      3
39  彭美慧  女  91   52  95  53  60  351  70.2  42.0      2
40  劉靜芬  女  63   91  96  63  56  369  73.8  31.0      1
41  許淑芬  女  97   91  70  85  84  427  85.4   3.0      0
42  邱裕豪  男  57  100  65  80  64  366  73.2  33.0      1
43  吳雅萍  女  55   99  86  95  89  424  84.8   6.0      1
44  施子軒  男  69   92  63  61  95  380  76.0  27.0      0
45  莊柏融  男  70   94  89  62  97  412  82.4  11.0      0
46  鍾浩銘  男  69   65  61  85  89  369  73.8  31.0      0
47  周美玲  女  72   58  94  61  99  384  76.8  25.0      1
48  劉婉婷  女  95   76  78  72  51  372  74.4  29.0      1
49  曾明哲  男  50   89  84  94  64  381  76.2  26.0      1
50  詹柏翰  男  96   69  80  66  51  362  72.4  37.0      1

In [30]:
def get_failing_subjects(row):
    subjects = ['語文', '英語', '數學', '地理', '歷史']
    failing = [subj for subj in subjects if row[subj] < 60]    
    return ','.join(failing) if failing else "無"
    
    
scores_df["不及格的科目名稱"] = scores_df[['語文', '英語', '數學', '地理', '歷史']].apply(get_failing_subjects,axis=1)
scores_df

     姓名 性別  語文   英語  數學  地理  歷史   總分    平均    排名  及格科目數     不及格的科目名稱
1   劉彥宏  男  64   69  72  73  86  364  72.8  36.0      0            無
2   曾彥廷  男  60   77  56  89  89  371  74.2  30.0      1           數學
3   吳子睿  男  75   94  66  99  91  425  85.0   4.0      0            無
4   蕭志明  男  88   98  51  70  89  396  79.2  19.0      1           數學
5   王文傑  男  87   53  53  67  63  323  64.6  48.0      2        英語,數學
6   朱冠霖  男  80   74  96  60  89  399  79.8  16.0      0            無
7   謝欣蓉  女  59   65  51  83  61  319  63.8  49.0      2        語文,數學
8   羅淑芬  女  52   68  69  68  98  355  71.0  40.0      1           語文
9   許美慧  女  80   71  95  88  65  399  79.8  16.0      0            無
10  廖志豪  男  93   60  84  52  97  386  77.2  22.0      1           地理
11  葉柏翰  男  80   97  98  55  88  418  83.6   8.0      1           地理
12  呂承恩  男  51   60  54  50  56  271  54.2  50.0      4  語文,數學,地理,歷史
13  蘇雅婷  女  50   62  75  95  84  366  73.2  33.0      1           語文
14  高浩宇  男  82  100  92  97  92  463  92.6   1.0      0            無
15  王婉茹  女  65   79  89  87  68  388  77.6  21.0      0            無
16  莊承翰  男  69   56  70  54  83  332  66.4  47.0      2        英語,地理
17  黃裕傑  男  86   83  87  83  64  403  80.6  14.0      0            無
18  王冠廷  男  72   70  64  70  69  345  69.0  45.0      0            無
19  呂婉慧  女  67   92  85  99  82  425  85.0   4.0      0            無
20  莊子謙  男  67   81  57  77  60  342  68.4  46.0      1           數學
21  蘇彥宏  男  78   65  92  98  69  402  80.4  15.0      0            無
22  李柏融  男  91   74  96  84  76  421  84.2   7.0      0            無
23  曾明軒  男  98   82  73  71  62  386  77.2  22.0      0            無
24  呂佳瑩  女  95   72  52  74  92  385  77.0  24.0      1           數學
25  洪怡君  女  50   77  95  99  86  407  81.4  12.0      1           語文
26  洪柏宏  男  58  100  61  66  67  352  70.4  41.0      1           語文
27  江雅琪  女  89   98  88  71  61  407  81.4  12.0      0            無
28  郭怡萱  女  88   87  60  86  68  389  77.8  20.0      0            無
29  簡婉慧  女  90   89  91  98  93  461  92.2   2.0      0            無
30  楊靜宜  女  51   98  65  98  54  366  73.2  33.0      2        語文,歷史
31  曾靜儀  女  86   63  65  50  95  359  71.8  39.0      1           地理
32  蕭怡伶  女  61   88  95  75  78  397  79.4  18.0      0            無
33  洪裕豪  男  97   83  96  77  61  414  82.8  10.0      0            無
34  簡建宏  男  77   60  66  75  82  360  72.0  38.0      0            無
35  劉浩然  男  86   63  70  67  65  351  70.2  42.0      0            無
36  蕭浩宇  男  88   89  78  74  89  418  83.6   8.0      0            無
37  呂怡靜  女  50   94  72  76  87  379  75.8  28.0      1           語文
38  邱宗翰  男  57   59  58  81  94  349  69.8  44.0      3     語文,英語,數學
39  彭美慧  女  91   52  95  53  60  351  70.2  42.0      2        英語,地理
40  劉靜芬  女  63   91  96  63  56  369  73.8  31.0      1           歷史
41  許淑芬  女  97   91  70  85  84  427  85.4   3.0      0            無
42  邱裕豪  男  57  100  65  80  64  366  73.2  33.0      1           語文
43  吳雅萍  女  55   99  86  95  89  424  84.8   6.0      1           語文
44  施子軒  男  69   92  63  61  95  380  76.0  27.0      0            無
45  莊柏融  男  70   94  89  62  97  412  82.4  11.0      0            無
46  鍾浩銘  男  69   65  61  85  89  369  73.8  31.0      0            無
47  周美玲  女  72   58  94  61  99  384  76.8  25.0      1           英語
48  劉婉婷  女  95   76  78  72  51  372  74.4  29.0      1           歷史
49  曾明哲  男  50   89  84  94  64  381  76.2  26.0      1           語文
50  詹柏翰  男  96   69  80  66  51  362  72.4  37.0      1           歷史

In [ ]:
[subj for subj in [30, 40, 50] if subj <= 40] #list綜合表達式
fallings = []
','.join(fallings) if fallings else "無"

In [ ]:
# 樞紐分析
import numpy as np
import pandas as pd

data = pd. Series(np.random.randn(9),
                 index=[['a','a','a','b','b','c','c','d','d'],
                        [1,2,3,1,3,1,2,2,3]])

data

<bound method Series.unstack of a  1   -0.480302
   2   -0.463907
   3    2.524017
b  1   -1.474642
   3    1.474328
c  1   -0.821794
   2   -0.149702
d  2    2.671802
   3    0.864085
dtype: float64>

In [36]:
data1 = data.unstack()
data1

          1         2         3
a -0.480302 -0.463907  2.524017
b -1.474642       NaN  1.474328
c -0.821794 -0.149702       NaN
d       NaN  2.671802  0.864085

In [37]:
data1.stack()

a  1   -0.480302
   2   -0.463907
   3    2.524017
b  1   -1.474642
   2         NaN
   3    1.474328
c  1   -0.821794
   2   -0.149702
   3         NaN
d  1         NaN
   2    2.671802
   3    0.864085
dtype: float64