In [1]:
import numpy as np
import pandas as pd

frame = pd.DataFrame(np.arange(12).reshape((4, 3)),
                    index=[['a','a','b','b'],[1, 2, 1, 2]],
                    columns=[['台北','台北','台中'],['Green','Red','Green']])
frame.index.names = ['key1', 'key2']
frame.columns.names = ['縣市','顏色']
frame

縣市           台北        台中
顏色        Green Red Green
key1 key2
a    1        0   1     2
     2        3   4     5
b    1        6   7     8
     2        9  10    11

In [2]:
frame1 = frame.stack(['顏色','縣市'])
frame1

key1  key2  顏色     縣市
a     1     Green  台北     0
            Red    台北     1
            Green  台中     2
      2     Green  台北     3
            Red    台北     4
            Green  台中     5
b     1     Green  台北     6
            Red    台北     7
            Green  台中     8
      2     Green  台北     9
            Red    台北    10
            Green  台中    11
dtype: int64

In [3]:
frame1.unstack('key1')

key1           a   b
key2 顏色    縣市
1    Green 台中  2   8
           台北  0   6
     Red   台北  1   7
2    Green 台中  5  11
           台北  3   9
     Red   台北  4  10

In [4]:
import numpy as np
import pandas as pd

df = pd.DataFrame({'key1':['a', 'a', 'b', 'b', 'a'],
                  'key2':['one', 'two', 'one', 'two', 'one'],
                  'data1': np.random.randn(5),
                  'data2':np.random.randn(5)})
df

  key1 key2     data1     data2
0    a  one  0.438614 -0.699879
1    a  two  0.490718  0.645152
2    b  one -0.727808 -1.970505
3    b  two -0.842406  0.547489
4    a  one  0.193868 -0.583771

In [8]:
df[['key1','data1','data2']].groupby('key1').sum()

         data1     data2
key1
a     1.123200 -0.638498
b    -1.570214 -1.423017

In [ ]:
df[['key1','data1','data2']].groupby('key1').mean()

In [5]:
df.groupby('key1').sum()

           key2     data1     data2
key1
a     onetwoone  1.123200 -0.638498
b        onetwo -1.570214 -1.423017

In [6]:
df1 = df.groupby(['key1','key2']).sum()
df1.columns.name = 'data'
df1

data          data1     data2
key1 key2
a    one   0.632482 -1.283650
     two   0.490718  0.645152
b    one  -0.727808 -1.970505
     two  -0.842406  0.547489

In [7]:
df1.stack().unstack(['key1','key2'])

key1          a                   b
key2        one       two       one       two
data
data1  0.632482  0.490718 -0.727808 -0.842406
data2 -1.283650  0.645152 -1.970505  0.547489